#!/usr/bin/env python3
"""Estimate car speed from camera pan rate and Grounded-SAM wheel centers.

Stage 1 stores the car bounding box generated by GroundingDINO. This stage crops
to that car bbox, runs GroundingDINO with a wheel/tire prompt inside the crop,
refines the detected wheel boxes with SAM2, and measures the distance between the
selected wheel centers.

    depth_m = focal_px * wheelbase_m / wheelbase_px
    speed_m_s = omega_rad_s * depth_m

Manual wheel centers or a manual wheelbase in pixels can still be supplied when
the detector needs correction. Stage 5 writes a wheel measurement overlay and a separate final result diagram
with blur, pan rate, exposure, depth, and speed estimates.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import ExifTags, Image, ImageDraw, ImageFont, ImageOps


EXIF_BY_NAME = {name: tag for tag, name in ExifTags.TAGS.items()}


def rational_to_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        pass
    if isinstance(value, tuple) and len(value) == 2 and value[1] != 0:
        return float(value[0]) / float(value[1])
    return None


def iter_ifds(exif):
    yield exif
    if not hasattr(exif, 'get_ifd'):
        return

    ifd_ids = [0x8769, 0x8825, 0xA005]  # Exif, GPS, Interop
    if hasattr(ExifTags, 'IFD'):
        for attr in ['Exif', 'GPSInfo', 'Interop']:
            if hasattr(ExifTags.IFD, attr):
                ifd_ids.append(getattr(ExifTags.IFD, attr))

    seen = set()
    for ifd_id in ifd_ids:
        key = str(ifd_id)
        if key in seen:
            continue
        seen.add(key)
        try:
            nested = exif.get_ifd(ifd_id)
        except Exception:
            continue
        if nested:
            yield nested


def get_exif_value(exif, name: str):
    tag = EXIF_BY_NAME.get(name)
    if tag is None:
        return None
    for ifd in iter_ifds(exif):
        value = ifd.get(tag)
        if value is not None:
            return value
    return None


def focal_px_from_exif(image: Image.Image, sensor_width_mm: float | None) -> tuple[float | None, dict[str, Any]]:
    exif = image.getexif()
    width_px = image.width

    focal_mm = rational_to_float(get_exif_value(exif, 'FocalLength'))
    focal_35 = rational_to_float(get_exif_value(exif, 'FocalLengthIn35mmFilm'))
    fp_x = rational_to_float(get_exif_value(exif, 'FocalPlaneXResolution'))
    fp_unit = get_exif_value(exif, 'FocalPlaneResolutionUnit')

    meta = {
        'exif_focal_mm': focal_mm,
        'exif_focal_35mm': focal_35,
        'exif_focal_plane_x_resolution': fp_x,
        'exif_focal_plane_resolution_unit': fp_unit,
    }

    unit_to_mm = {
        2: 25.4,  # inch
        3: 10.0,  # centimeter
        4: 1.0,   # millimeter
        5: 0.001, # micrometer
    }
    if focal_mm and fp_x and fp_unit in unit_to_mm:
        pixel_pitch_mm = unit_to_mm[fp_unit] / fp_x
        meta.update({
            'focal_source': 'exif_focal_length_and_focal_plane_resolution',
            'pixel_pitch_mm': pixel_pitch_mm,
            'sensor_width_mm': pixel_pitch_mm * width_px,
        })
        return focal_mm / pixel_pitch_mm, meta

    if focal_35:
        meta.update({
            'focal_source': 'exif_35mm_equivalent',
            'sensor_width_mm': 36.0,
        })
        return width_px * focal_35 / 36.0, meta

    if focal_mm and sensor_width_mm:
        meta.update({
            'focal_source': 'exif_focal_length_with_sensor_width_arg',
            'sensor_width_mm': sensor_width_mm,
        })
        return width_px * focal_mm / sensor_width_mm, meta

    meta['focal_source'] = None
    return None, meta


def load_focal_px(image: Image.Image, trajectory: dict[str, Any], args: argparse.Namespace) -> tuple[float, dict[str, Any]]:
    if args.focal_px is not None:
        return float(args.focal_px), {'focal_source': 'argument_focal_px'}

    sensor_width = args.sensor_width_mm
    if args.focal_mm is not None:
        if sensor_width is None:
            raise ValueError('--sensor_width_mm is required when --focal_mm is supplied without --focal_px')
        return image.width * float(args.focal_mm) / float(sensor_width), {
            'focal_source': 'argument_focal_mm_and_sensor_width',
            'focal_mm': float(args.focal_mm),
            'sensor_width_mm': float(sensor_width),
        }

    focal_px, meta = focal_px_from_exif(image, sensor_width)
    if focal_px is not None:
        return focal_px, meta

    if 'focal_px' in trajectory:
        return float(trajectory['focal_px']), {
            **meta,
            'focal_source': 'trajectory_json_fallback',
            'focal_mm': trajectory.get('focal_mm'),
            'sensor_width_mm': trajectory.get('sensor_w_mm'),
        }

    raise ValueError(
        'Could not determine focal length in pixels. Supply --focal_px, or '
        '--focal_mm with --sensor_width_mm, or use an image with EXIF focal metadata.'
    )


def parse_point(values: list[float] | None) -> tuple[float, float] | None:
    if values is None:
        return None
    if len(values) != 2:
        raise ValueError('Wheel center arguments must contain exactly two values: x y')
    return float(values[0]), float(values[1])


def clip_box(box: list[float] | tuple[float, float, float, float], width: int, height: int) -> tuple[int, int, int, int]:
    x0, y0, x1, y1 = [float(v) for v in box]
    x0 = int(max(0, min(width - 1, math.floor(x0))))
    y0 = int(max(0, min(height - 1, math.floor(y0))))
    x1 = int(max(x0 + 1, min(width, math.ceil(x1))))
    y1 = int(max(y0 + 1, min(height, math.ceil(y1))))
    return x0, y0, x1, y1


def bbox_from_mask(mask_path: str | Path, width: int, height: int) -> tuple[int, int, int, int]:
    mask = np.array(Image.open(mask_path).convert('L')) > 127
    ys, xs = np.where(mask)
    if len(xs) == 0:
        raise ValueError('Car mask is empty and no Stage 1 car bbox metadata was available.')
    return clip_box([xs.min(), ys.min(), xs.max() + 1, ys.max() + 1], width, height)


def load_stage1_car_bbox(meta_path: str | Path, mask_path: str | Path, width: int, height: int) -> tuple[tuple[int, int, int, int], dict[str, Any]]:
    path = Path(meta_path)
    if path.exists():
        with path.open() as f:
            meta = json.load(f)
        box = meta.get('car_bbox_xyxy')
        if box is not None:
            return clip_box(box, width, height), {
                'car_bbox_source': meta.get('car_bbox_source', 'stage1_grounding_dino'),
                'car_detection_json': str(path),
                'stage1_text_prompt': meta.get('text_prompt'),
                'stage1_detections': meta.get('detections', []),
            }
        print(f"[warn] {path} has no car_bbox_xyxy; falling back to car mask bbox.")
    else:
        print(f"[warn] {path} not found; falling back to car mask bbox.")

    return bbox_from_mask(mask_path, width, height), {
        'car_bbox_source': 'mask_bbox_fallback',
        'car_detection_json': str(path),
        'stage1_detections': [],
    }


def run_grounding_dino(image_pil: Image.Image, text_prompt: str, box_threshold: float, text_threshold: float, device: str):
    from transformers import AutoModelForZeroShotObjectDetection, AutoProcessor

    model_id = 'IDEA-Research/grounding-dino-tiny'
    print(f"Loading Grounding DINO ({model_id}) for wheel detection ...")
    processor = AutoProcessor.from_pretrained(model_id)
    model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id).to(device)
    model.eval()

    inputs = processor(images=image_pil, text=text_prompt, return_tensors='pt').to(device)
    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs,
        input_ids=inputs.input_ids,
        threshold=box_threshold,
        text_threshold=text_threshold,
        target_sizes=[(image_pil.height, image_pil.width)],
    )
    boxes = results[0]['boxes'].cpu().numpy()
    scores = results[0]['scores'].cpu().numpy()
    labels = results[0]['labels']
    print(f"Wheel GroundingDINO detections in car crop: {len(boxes)}")
    for i, (box, score, label) in enumerate(zip(boxes, scores, labels)):
        print(f"  [{i}] {label}  score={score:.3f}  box={box.round(1).tolist()}")
    return boxes, scores, labels


def run_sam2(image_pil: Image.Image, boxes_xyxy: np.ndarray, device: str) -> np.ndarray:
    from transformers import Sam2Model, Sam2Processor

    model_id = 'facebook/sam2-hiera-small'
    print(f"Loading SAM 2 ({model_id}) for wheel masks ...")
    processor = Sam2Processor.from_pretrained(model_id)
    model = Sam2Model.from_pretrained(model_id).to(device)
    model.eval()

    inputs = processor(
        images=image_pil,
        input_boxes=[boxes_xyxy.tolist()],
        return_tensors='pt',
    ).to(device)
    with torch.no_grad():
        outputs = model(**inputs, multimask_output=False)
    masks_list = processor.post_process_masks(outputs.pred_masks, original_sizes=inputs['original_sizes'])
    return masks_list[0].squeeze(1).cpu().numpy()


def candidate_from_mask(mask: np.ndarray, box_crop: np.ndarray, score: float, label: str, crop_xyxy: tuple[int, int, int, int], index: int) -> dict[str, Any]:
    x0, y0, _, _ = crop_xyxy
    ys, xs = np.where(mask > 0)
    if len(xs):
        cx_crop = float(xs.mean())
        cy_crop = float(ys.mean())
        area = float(len(xs))
        radius = math.sqrt(area / math.pi)
    else:
        bx0, by0, bx1, by1 = [float(v) for v in box_crop]
        cx_crop = (bx0 + bx1) / 2.0
        cy_crop = (by0 + by1) / 2.0
        area = max(1.0, (bx1 - bx0) * (by1 - by0))
        radius = math.sqrt(area / math.pi)

    bx0, by0, bx1, by1 = [float(v) for v in box_crop]
    return {
        'index': int(index),
        'label': str(label),
        'score': float(score),
        'box_crop_xyxy': [bx0, by0, bx1, by1],
        'box_xyxy': [bx0 + x0, by0 + y0, bx1 + x0, by1 + y0],
        'x': float(cx_crop + x0),
        'y': float(cy_crop + y0),
        'radius_px': float(radius),
        'mask_area_px': float(area),
        'source': 'grounding_dino_sam2',
    }


def merge_wheel_candidates(candidates: list[dict[str, Any]], merge_dist_px: float = 85.0) -> list[dict[str, Any]]:
    merged: list[dict[str, Any]] = []
    for cand in sorted(candidates, key=lambda c: float(c.get('score', 0.0)), reverse=True):
        found = None
        for item in merged:
            if math.hypot(float(cand['x']) - float(item['x']), float(cand['y']) - float(item['y'])) <= merge_dist_px:
                found = item
                break
        if found is None:
            merged.append(cand.copy())
            continue
        found.setdefault('merged_indices', [found['index']])
        found['merged_indices'].append(cand['index'])
        if float(cand.get('score', 0.0)) > float(found.get('score', 0.0)):
            keep_indices = found['merged_indices']
            found.update(cand)
            found['merged_indices'] = keep_indices
    return merged



def choose_wheel_pair(candidates: list[dict[str, Any]], car_bbox: tuple[int, int, int, int], bbox_ratio_prior: float) -> tuple[dict[str, Any], dict[str, Any]] | None:
    if len(candidates) < 2:
        return None
    x0, y0, x1, y1 = car_bbox
    bw, bh = x1 - x0, y1 - y0
    best_pair = None
    best_score = -float('inf')
    max_det_score = max(float(c.get('score', 0.0)) for c in candidates) or 1.0
    expected_dx = max(1.0, float(bbox_ratio_prior) * bw)

    for i, a in enumerate(candidates):
        for b in candidates[i + 1:]:
            dx = abs(float(a['x']) - float(b['x']))
            dy = abs(float(a['y']) - float(b['y']))
            if dx < 0.25 * bw:
                continue
            if dy > 0.35 * bh:
                continue
            r1 = max(float(a.get('radius_px', 1.0)), 1.0)
            r2 = max(float(b.get('radius_px', 1.0)), 1.0)
            if max(r1, r2) / min(r1, r2) > 3.0:
                continue
            score_term = (float(a.get('score', 0.0)) + float(b.get('score', 0.0))) / max_det_score
            area_term = math.sqrt(max(float(a.get('mask_area_px', 1.0)), 1.0)) + math.sqrt(max(float(b.get('mask_area_px', 1.0)), 1.0))
            dx_prior_penalty = abs(dx - expected_dx)
            pair_score = -0.85 * dx_prior_penalty - 0.75 * dy + 180.0 * score_term + 0.02 * area_term
            if pair_score > best_score:
                best_score = pair_score
                best_pair = (a, b)

    if best_pair is None:
        return None
    return tuple(sorted(best_pair, key=lambda c: float(c['x'])))


def detect_wheels_grounded_sam(image: Image.Image, car_bbox: tuple[int, int, int, int], args: argparse.Namespace) -> tuple[tuple[float, float], tuple[float, float], dict[str, Any]]:
    crop = image.crop(car_bbox)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Wheel detector device: {device}")
    print(f"Wheel search crop xyxy: {list(car_bbox)}  size={crop.width}x{crop.height}")

    boxes, scores, labels = run_grounding_dino(
        crop,
        args.wheel_text_prompt,
        args.wheel_box_threshold,
        args.wheel_text_threshold,
        device,
    )
    if len(boxes) < 2:
        raise ValueError(
            f'GroundingDINO found {len(boxes)} wheel candidates in the Stage 1 car crop. '
            'Try lowering --wheel_box_threshold or pass manual --left_wheel/--right_wheel.'
        )

    masks = run_sam2(crop, boxes, device)
    raw_candidates = [
        candidate_from_mask(mask, box, score, label, car_bbox, i)
        for i, (mask, box, score, label) in enumerate(zip(masks, boxes, scores, labels))
    ]
    candidates = merge_wheel_candidates(raw_candidates)

    pair = choose_wheel_pair(candidates, car_bbox, args.wheelbase_bbox_ratio_prior)
    if pair is None:
        raise ValueError(
            'GroundingDINO/SAM produced wheel candidates, but no plausible wheel pair. '
            'Try manual --left_wheel/--right_wheel or --wheelbase_px.'
        )

    left, right = pair
    detail = {
        'method': 'grounding_dino_sam2_in_stage1_car_bbox',
        'wheel_text_prompt': args.wheel_text_prompt,
        'wheel_box_threshold': float(args.wheel_box_threshold),
        'wheel_text_threshold': float(args.wheel_text_threshold),
        'car_crop_xyxy': list(map(int, car_bbox)),
        'raw_candidate_count': len(raw_candidates),
        'candidate_count': len(candidates),
        'raw_candidates': raw_candidates,
        'candidates': candidates,
        'wheelbase_bbox_ratio_prior': float(args.wheelbase_bbox_ratio_prior),
        'left_wheel_xy': [float(left['x']), float(left['y'])],
        'right_wheel_xy': [float(right['x']), float(right['y'])],
        'left_candidate_index': int(left['index']),
        'right_candidate_index': int(right['index']),
    }
    return (float(left['x']), float(left['y'])), (float(right['x']), float(right['y'])), detail


def load_font(size: int, bold: bool = False):
    names = ['DejaVuSans-Bold.ttf'] if bold else ['DejaVuSans.ttf']
    paths = [
        Path('/usr/share/fonts/truetype/dejavu') / name
        for name in names
    ]
    for font_path in paths:
        try:
            return ImageFont.truetype(str(font_path), size=size)
        except OSError:
            pass
    return ImageFont.load_default()


def text_with_shadow(draw: ImageDraw.ImageDraw, xy: tuple[float, float], text: str,
                     font, fill: tuple[int, int, int, int], shadow_alpha: int = 180) -> None:
    x, y = xy
    draw.text((x + 3, y + 3), text, font=font, fill=(0, 0, 0, shadow_alpha))
    draw.text((x, y), text, font=font, fill=fill)


def format_exposure(exposure_s: float | None) -> str:
    if exposure_s is None or exposure_s <= 0:
        return 'n/a'
    inv = 1.0 / exposure_s
    if abs(inv - round(inv)) <= 0.02 * max(inv, 1.0):
        return f'1/{int(round(inv))} s  ({exposure_s * 1000:.1f} ms)'
    return f'{exposure_s:.4f} s  ({exposure_s * 1000:.1f} ms)'


def draw_wheel_overlay(image: Image.Image, car_bbox: tuple[int, int, int, int] | None,
                       left: tuple[float, float] | None, right: tuple[float, float] | None,
                       wheelbase_px: float, out_path: Path) -> None:
    vis = image.copy().convert('RGBA')
    overlay = Image.new('RGBA', vis.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    W, H = vis.size

    if car_bbox is not None:
        x0, y0, x1, y1 = car_bbox
        draw.rectangle((x0, y0, x1, y1), fill=(80, 255, 120, 22), outline=(0, 0, 0, 170), width=13)
        draw.rectangle((x0, y0, x1, y1), outline=(92, 255, 130, 245), width=7)

    if left is not None and right is not None:
        lx, ly = left
        rx, ry = right
        draw.line((lx, ly, rx, ry), fill=(0, 0, 0, 190), width=18)
        draw.line((lx, ly, rx, ry), fill=(255, 214, 48, 255), width=10)
        label_font = load_font(max(24, int(min(W, H) * 0.008)), bold=True)
        for label, (x, y), color in [
            ('L', (lx, ly), (77, 220, 255, 255)),
            ('R', (rx, ry), (255, 96, 88, 255)),
        ]:
            r = max(30, int(min(W, H) * 0.009))
            draw.ellipse((x - r - 5, y - r - 5, x + r + 5, y + r + 5), fill=(0, 0, 0, 150))
            draw.ellipse((x - r, y - r, x + r, y + r), fill=(8, 13, 18, 230), outline=color, width=7)
            draw.ellipse((x - 7, y - 7, x + 7, y + 7), fill=color)
            text_with_shadow(draw, (x + r + 12, y - r - 4), label, label_font, color)

        mx, my = (lx + rx) / 2.0, (ly + ry) / 2.0
        wheelbase_label = f'wheelbase  {wheelbase_px:.1f} px'
        bbox = draw.textbbox((0, 0), wheelbase_label, font=label_font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
        pad = 14
        label_xy = (mx - tw / 2.0 - pad, my - th - 64)
        draw.rounded_rectangle(
            (label_xy[0], label_xy[1], label_xy[0] + tw + 2 * pad, label_xy[1] + th + 2 * pad),
            radius=18,
            fill=(8, 12, 18, 210),
            outline=(255, 214, 48, 190),
            width=3,
        )
        text_with_shadow(draw, (label_xy[0] + pad, label_xy[1] + pad - 2), wheelbase_label, label_font, (255, 232, 92, 255))

    composed = Image.alpha_composite(vis, overlay).convert('RGB')
    out_path.parent.mkdir(parents=True, exist_ok=True)
    composed.save(out_path, quality=95)


def draw_final_result(image: Image.Image, car_bbox: tuple[int, int, int, int] | None,
                      left: tuple[float, float] | None, right: tuple[float, float] | None,
                      wheelbase_px: float, out_path: Path,
                      trajectory: dict[str, Any] | None = None,
                      speed: dict[str, Any] | None = None) -> None:
    vis = image.copy().convert('RGBA')
    overlay = Image.new('RGBA', vis.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    W, H = vis.size
    margin = max(28, int(min(W, H) * 0.01))

    if car_bbox is not None:
        x0, y0, x1, y1 = car_bbox
        draw.rectangle((x0, y0, x1, y1), fill=(80, 255, 120, 28), outline=(4, 18, 8, 180), width=14)
        draw.rectangle((x0, y0, x1, y1), outline=(92, 255, 130, 245), width=7)

    if left is not None and right is not None:
        lx, ly = left
        rx, ry = right
        draw.line((lx, ly, rx, ry), fill=(0, 0, 0, 190), width=18)
        draw.line((lx, ly, rx, ry), fill=(255, 214, 48, 255), width=10)
        dot_font = load_font(max(24, int(min(W, H) * 0.008)), bold=True)
        for label, (x, y), color in [
            ('L', (lx, ly), (77, 220, 255, 255)),
            ('R', (rx, ry), (255, 96, 88, 255)),
        ]:
            r = max(30, int(min(W, H) * 0.009))
            draw.ellipse((x - r - 5, y - r - 5, x + r + 5, y + r + 5), fill=(0, 0, 0, 150))
            draw.ellipse((x - r, y - r, x + r, y + r), fill=(8, 13, 18, 230), outline=color, width=7)
            draw.ellipse((x - 7, y - 7, x + 7, y + 7), fill=color)
            text_with_shadow(draw, (x + r + 12, y - r - 4), label, dot_font, color)

        mx, my = (lx + rx) / 2.0, (ly + ry) / 2.0
        label_font = load_font(max(24, int(min(W, H) * 0.008)), bold=True)
        wheelbase_label = f'wheelbase  {wheelbase_px:.1f} px'
        bbox = draw.textbbox((0, 0), wheelbase_label, font=label_font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
        pad = 14
        label_xy = (mx - tw / 2.0 - pad, my - th - 64)
        draw.rounded_rectangle(
            (label_xy[0], label_xy[1], label_xy[0] + tw + 2 * pad, label_xy[1] + th + 2 * pad),
            radius=18,
            fill=(8, 12, 18, 210),
            outline=(255, 214, 48, 190),
            width=3,
        )
        text_with_shadow(draw, (label_xy[0] + pad, label_xy[1] + pad - 2), wheelbase_label, label_font, (255, 232, 92, 255))

    trajectory = trajectory or {}
    speed = speed or {}
    if car_bbox is not None:
        x0, y0, x1, y1 = car_bbox
        right_space = W - x1 - 2 * margin
        desired_w = min(940, max(540, int(W * 0.18)))
        panel_w = min(desired_w, max(440, right_space))
        if right_space >= 440:
            panel_x = x1 + margin
        else:
            panel_w = min(desired_w, max(440, x0 - 2 * margin))
            panel_x = max(margin, x0 - margin - panel_w)
        panel_h = min(max(560, int(H * 0.15)), H - 2 * margin)
        panel_y = min(max(y0, margin), H - panel_h - margin)
    else:
        panel_w = min(940, max(540, int(W * 0.22)))
        panel_h = min(max(560, int(H * 0.15)), H - 2 * margin)
        panel_x = W - panel_w - margin
        panel_y = margin

    panel_x2 = min(W - margin, panel_x + panel_w)
    panel_w = panel_x2 - panel_x
    panel_y2 = min(H - margin, panel_y + panel_h)
    panel_h = panel_y2 - panel_y
    draw.rounded_rectangle(
        (panel_x, panel_y, panel_x + panel_w, panel_y + panel_h),
        radius=max(20, int(panel_w * 0.035)),
        fill=(6, 10, 16, 224),
        outline=(255, 255, 255, 82),
        width=3,
    )
    draw.rectangle((panel_x, panel_y, panel_x + 10, panel_y + panel_h), fill=(255, 214, 48, 235))

    if car_bbox is not None:
        x0, y0, x1, y1 = car_bbox
        anchor_y = y0 + 0.18 * (y1 - y0)
        draw.line((x1, anchor_y, panel_x, panel_y + 46), fill=(255, 214, 48, 180), width=4)

    base = max(18, min(34, int(panel_w / 18), int(min(W, H) / 115)))
    title_font = load_font(base + 8, bold=True)
    label_font = load_font(max(15, base - 6), bold=True)
    value_font = load_font(base, bold=True)
    velocity_label_font = load_font(max(base - 1, label_font.size + 5 if hasattr(label_font, 'size') else base), bold=True)
    velocity_value_font = load_font(base + 20, bold=True)
    sub_font = load_font(max(14, base - 7), bold=False)

    x = panel_x + max(28, int(panel_w * 0.06))
    y = panel_y + max(24, int(panel_h * 0.045))
    text_with_shadow(draw, (x, y), 'FINAL SPEED ESTIMATION', title_font, (246, 250, 255, 255))
    y += base + 24
    draw.line((x, y, panel_x + panel_w - 28, y), fill=(255, 214, 48, 190), width=3)
    y += max(20, int(base * 0.75))

    stats = [
        ('Global blur kernel', f"{float(trajectory.get('b_total_px', float('nan'))):.1f} px", None, False),
        ('Angular velocity', f"{float(trajectory.get('omega_deg_s', speed.get('omega_deg_s', float('nan')))):.1f} deg/s", None, False),
        ('Exposure time', format_exposure(trajectory.get('exposure_s')), None, False),
        ('Estimated depth', f"{float(speed.get('depth_m', float('nan'))):.2f} m", None, False),
        ('Vehicle velocity', f"{float(speed.get('speed_km_h', float('nan'))):.1f} km/h", f"{float(speed.get('speed_mph', float('nan'))):.1f} mph", True),
    ]

    for label, value, sub, emphasize in stats:
        current_label_font = velocity_label_font if emphasize else label_font
        current_value_font = velocity_value_font if emphasize else value_font
        draw.text((x, y), label.upper(), font=current_label_font, fill=(143, 166, 190, 255))
        y += max(18, int(current_label_font.size * 0.86) if hasattr(current_label_font, 'size') else int(base * 0.70))
        text_with_shadow(draw, (x, y), value, current_value_font, (255, 255, 255, 255))
        y += max(24, int(current_value_font.size * 1.12) if hasattr(current_value_font, 'size') else int(base * 1.05))
        if sub:
            draw.text((x, y), sub, font=sub_font, fill=(188, 202, 216, 240))
            y += max(22, int(base * 0.86))
        y += max(10, int(base * 0.30))

    composed = Image.alpha_composite(vis, overlay).convert('RGB')
    out_path.parent.mkdir(parents=True, exist_ok=True)
    composed.save(out_path, quality=95)

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--image', default='pan_1.jpg', help='Panning image containing the car.')
    p.add_argument('--car_mask', default=None,
                   help='Car mask path; defaults to <out_dir>/car_mask.png')
    p.add_argument('--car_detection_json', default=None,
                   help='Stage 1 metadata; defaults to <out_dir>/car_detection.json')
    p.add_argument('--trajectory', default=None,
                   help='Trajectory JSON; defaults to <out_dir>/trajectory.json')
    p.add_argument('--output_root', default='outputs',
                   help='Parent directory for per-image output subdirectories')
    p.add_argument('--out_dir', default=None,
                   help='Explicit output directory; defaults to <output_root>/<image_stem>')
    p.add_argument('--wheelbase_mm', type=float, default=3400.0)
    p.add_argument('--wheelbase_px', type=float, default=None,
                   help='Manual wheel-center distance in pixels; skips wheel detection.')
    p.add_argument('--left_wheel', nargs=2, type=float, default=None,
                   metavar=('X', 'Y'), help='Manual left wheel center in image pixels.')
    p.add_argument('--right_wheel', nargs=2, type=float, default=None,
                   metavar=('X', 'Y'), help='Manual right wheel center in image pixels.')
    p.add_argument('--wheel_text_prompt', default='wheel . tire . car wheel . racing wheel .',
                   help='GroundingDINO prompt used inside the Stage 1 car bbox.')
    p.add_argument('--wheel_box_threshold', type=float, default=0.18)
    p.add_argument('--wheel_text_threshold', type=float, default=0.15)
    p.add_argument('--wheelbase_bbox_ratio_prior', type=float, default=0.50,
                   help='Expected image wheelbase as a fraction of the Stage 1 car bbox width.')
    p.add_argument('--focal_px', type=float, default=None)
    p.add_argument('--focal_mm', type=float, default=None)
    p.add_argument('--sensor_width_mm', type=float, default=None,
                   help='Needed when EXIF lacks focal-plane metadata but focal_mm is known.')
    args = p.parse_args()

    if args.out_dir is not None:
        out_dir = Path(args.out_dir)
    elif args.trajectory is not None:
        out_dir = Path(args.trajectory).parent
    else:
        out_dir = Path(args.output_root) / Path(args.image).stem
    out_dir.mkdir(parents=True, exist_ok=True)
    if args.car_mask is None:
        args.car_mask = str(out_dir / 'car_mask.png')
    if args.car_detection_json is None:
        args.car_detection_json = str(out_dir / 'car_detection.json')
    if args.trajectory is None:
        args.trajectory = str(out_dir / 'trajectory.json')

    image = ImageOps.exif_transpose(Image.open(args.image)).convert('RGB')
    with open(args.trajectory) as f:
        trajectory = json.load(f)

    focal_px, focal_meta = load_focal_px(image, trajectory, args)
    omega_rad_s = trajectory.get('omega_rad_s')
    if omega_rad_s is None:
        raise ValueError(f'{args.trajectory} does not contain omega_rad_s')
    omega_rad_s = abs(float(omega_rad_s))

    left = parse_point(args.left_wheel)
    right = parse_point(args.right_wheel)
    car_bbox, car_meta = load_stage1_car_bbox(args.car_detection_json, args.car_mask, image.width, image.height)
    detection: dict[str, Any] = {'method': None, **car_meta}

    if args.wheelbase_px is not None:
        wheelbase_px = float(args.wheelbase_px)
        detection['method'] = 'manual_wheelbase_px'
    else:
        if left is None or right is None:
            left, right, wheel_detection = detect_wheels_grounded_sam(image, car_bbox, args)
            detection.update(wheel_detection)
        else:
            detection['method'] = 'manual_wheel_centers'
        wheelbase_px = float(math.hypot(right[0] - left[0], right[1] - left[1]))
        detection.update({
            'left_wheel_xy': [float(left[0]), float(left[1])],
            'right_wheel_xy': [float(right[0]), float(right[1])],
        })

    if wheelbase_px <= 0:
        raise ValueError('wheelbase_px must be positive')

    wheelbase_m = float(args.wheelbase_mm) / 1000.0
    depth_m = focal_px * wheelbase_m / wheelbase_px
    speed_m_s = omega_rad_s * depth_m
    speed_km_h = speed_m_s * 3.6
    speed_mph = speed_m_s * 2.2369362920544

    overlay_path = out_dir / 'car_speed_wheels.png'
    final_result_path = out_dir / 'final_result.png'

    result = {
        'speed_m_s': float(speed_m_s),
        'speed_km_h': float(speed_km_h),
        'speed_mph': float(speed_mph),
        'depth_m': float(depth_m),
        'omega_rad_s': float(omega_rad_s),
        'omega_deg_s': float(math.degrees(omega_rad_s)),
        'wheelbase_mm': float(args.wheelbase_mm),
        'wheelbase_px': float(wheelbase_px),
        'focal_px': float(focal_px),
        **focal_meta,
        'wheel_detection': detection,
        'assumptions': [
            'camera pan angular velocity from background blur matches car angular velocity',
            'wheelbase is approximately parallel to the image plane',
            'wheel centers are measured in the panning image coordinate frame',
        ],
        'outputs': {
            'wheel_overlay': str(overlay_path),
            'final_result': str(final_result_path),
        },
    }

    draw_wheel_overlay(image, car_bbox, left, right, wheelbase_px, overlay_path)
    draw_final_result(image, car_bbox, left, right, wheelbase_px, final_result_path, trajectory=trajectory, speed=result)

    out_path = out_dir / 'car_speed.json'
    with open(out_path, 'w') as f:
        json.dump(result, f, indent=2)

    print(f"Wheelbase: {wheelbase_px:.1f} px = {wheelbase_m:.3f} m")
    print(f"Focal: {focal_px:.1f} px ({result.get('focal_source')})")
    print(f"Estimated depth: {depth_m:.2f} m")
    print(f"Estimated speed: {speed_km_h:.1f} km/h  ({speed_mph:.1f} mph)")
    print(f"Saved: {out_path}")
    print(f"Saved: {overlay_path}")
    print(f"Saved: {final_result_path}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
